### ISSUE TITLE
iOS怎么与android服务器通信

### ISSUE THREAD

**Issue by GitterYang** [hvweihong/RemoteCamera#1]
iOS怎么作为客户端去实现实时预览？

**Comment by hvweihong** [comment]
你好，最简单的方法是直接使用ios手机浏览器输入192.168.43.1:8080进行连接，就能实时预览到安卓手机的图像（前提是ios手机必须先连上安卓手机的热点哦，以组成局域网）另外部分手机浏览器可能支持，手上没有苹果手机没测试，但是用火狐浏览器是可以的，可以用火狐试下，当然这个方法也能在电脑上用于预览。

如果想自己开发一个ios客户端的话，只要支持我的协议就可以了，协议要点为，1，通过192.168.43.1:8080进行socket连接，就可以得到实时的m-jpeg编码图像，然后对用m-jpeg解码库进行解码即可。至于对焦，拍照，相片回传的协议，看我的源码，很简单，随便定了个数据包而已，有什么问题可以右键联系我。

另外欢迎fork哦
